unknown_values = ('(:unac)', 
                  '(:unal)', 
                  '(:unap)', 
                  '(:unas)', 
                  '(:unav)', 
                  '(:unkn)', 
                  '(:none)', 
                  '(:null)', 
                  '(:tba)', 
                  '(:etal)')

contributortype_values = ('ContactPerson', 
                          'DataCollector', 
                          'DataCurator', 
                          'DataManager', 
                          'Distributor', 
                          'Editor', 
                          'Funder', 
                          'HostingInstitution', 
                          'Producer', 
                          'ProjectLeader', 
                          'ProjectManager', 
                          'ProjectMember', 
                          'RegistrationAgency', 
                          'RegistrationAuthority', 
                          'RelatedPerson', 
                          'Researcher', 
                          'ResearchGroup', 
                          'RightsHolder', 
                          'Sponsor', 
                          'Supervisor', 
                          'WorkPackageLeader', 
                          'Other')

datetype_values = ('Accepted', 
                   'Available', 
                   'Copyrighted', 
                   'Collected', 
                   'Created', 
                   'Issued', 
                   'Submitted', 
                   'Updated', 
                   'Valid')

resourcetypegeneral_values = ('Audiovisual', 
                              'Collection', 
                              'Dataset', 
                              'Event', 
                              'Image', 
                              'InteractiveResource', 
                              'Model', 
                              'PhysicalObject', 
                              'Service', 
                              'Software', 
                              'Sound', 
                              'Text', 
                              'Workflow', 
                              'Other')

relatedidentifiertype_values = ('ARK', 
                                'arXiv', 
                                'bibcode', 
                                'DOI', 
                                'EAN13', 
                                'EISSN', 
                                'Handle', 
                                'ISBN', 
                                'ISSN', 
                                'ISTC', 
                                'LISSN', 
                                'LSID', 
                                'PMID', 
                                'PURL', 
                                'UPC', 
                                'URL', 
                                'URN')

relatedidentifierrelationtype_values = ('IsCitedBy', 
                                        'Cites', 
                                        'IsSupplementTo', 
                                        'IsSupplementedBy', 
                                        'IsContinuedBy', 
                                        'Continues', 
                                        'HasMetadata', 
                                        'IsMetadataFor', 
                                        'IsNewVersionOf', 
                                        'IsPreviousVersionOf', 
                                        'IsPartOf', 
                                        'HasPart', 
                                        'IsReferencedBy', 
                                        'References', 
                                        'IsDocumentedBy', 
                                        'Documents', 
                                        'IsCompiledBy', 
                                        'Compiles', 
                                        'IsVariantFormOf', 
                                        'IsOriginalFormOf', 
                                        'IsIdenticalTo', 
                                        'IsReviewedBy', 
                                        'Reviews', 
                                        'IsDerivedFrom', 
                                        'IsSourceOf')

descriptiontype_values = ('Abstract', 
                          'Methods', 
                          'SeriesInformation', 
                          'TableOfContents', 
                          'Other')

# eof
